"""
Sync publications from Google Scholar into publications.json.

Google Scholar has no public API and blocks browser requests, so this cannot run
in the page itself. Run it on a schedule (see .github/workflows/sync-scholar.yml)
and commit the regenerated JSON.

    pip install scholarly
    python scripts/sync_scholar.py

Scholar merges authors with similar names. Anything whose title matches a string
in EXCLUDE, or whose author list does not contain an ALIAS, is dropped.
"""

import json, re, datetime, pathlib

from scholarly import scholarly

SCHOLAR_ID = "A6BwHbYAAAAJ"
OUT = pathlib.Path(__file__).resolve().parent.parent / "publications.json"

# Papers by a different V. Reddy.
EXCLUDE = [
    "cobalt doped nickel ferrite",
    "5g network optimization",
]

ALIASES = ["V Reddy", "Varshini Reddy", "V. Reddy"]

# Scholar reports the same work more than once (arXiv preprint + camera-ready).
# Keys are normalised titles; the value is the title to keep.
CANONICAL = {
    "the effect of scripts and formats on llm numeracy":
        "1,729 vs. 1729: The effect of scripts and formats on LLM numeracy",
    "are language model logits calibrated?":
        "Language model probabilities are not calibrated in numeric contexts",
}


def norm(t):
    return re.sub(r"[^a-z0-9 ]", "", t.lower()).strip()


def initialise(name):
    """'Charles W Schmidt' -> 'C. W. Schmidt'"""
    parts = name.split()
    if len(parts) < 2:
        return name
    return " ".join(p[0] + "." for p in parts[:-1]) + " " + parts[-1]


def format_authors(raw, limit=7):
    names = [initialise(n.strip()) for n in raw.split(" and ")]
    if len(names) > limit:
        names = names[:limit] + ["et al."]
    return ", ".join(names[:-1]) + (", " + names[-1] if len(names) > 1 else "")


def format_venue(bib):
    venue = bib.get("journal") or bib.get("booktitle") or bib.get("venue") or ""
    year = bib.get("pub_year", "")
    venue = re.sub(r"^Proceedings of (the )?", "", venue).strip()
    if not venue or "arxiv" in venue.lower():
        eprint = bib.get("eprint", "")
        venue = f"arXiv {eprint}" if eprint else "Preprint"
    return f"{venue} \u00b7 {year}" if year and year not in venue else venue


def main():
    author = scholarly.fill(scholarly.search_author_id(SCHOLAR_ID), sections=["publications"])

    seen, rows = {}, []
    for pub in author["publications"]:
        bib = pub["bib"]
        title = bib.get("title", "").strip()
        key = norm(title)

        if any(x in key for x in EXCLUDE):
            continue

        full = scholarly.fill(pub)
        bib = full["bib"]
        authors = bib.get("author", "")
        if not any(a.lower() in authors.lower() for a in ALIASES):
            continue

        key = norm(CANONICAL.get(key, title))
        cites = full.get("num_citations", 0)

        if key in seen:  # keep the better-cited / better-venued copy
            if cites <= seen[key]["cites"]:
                continue
            rows = [r for r in rows if norm(r["title"]) != key]

        row = {
            "title": CANONICAL.get(norm(title), title),
            "authors": format_authors(authors),
            "venue": format_venue(bib),
            "cites": cites,
            "url": full.get("pub_url") or full.get("eprint_url") or "",
        }
        seen[key] = row
        rows.append(row)

    rows.sort(key=lambda r: -r["cites"])

    OUT.write_text(json.dumps({
        "_comment": "Generated by scripts/sync_scholar.py. Sorted by citations, descending.",
        "updated": datetime.date.today().isoformat(),
        "publications": rows,
    }, indent=2, ensure_ascii=False) + "\n")

    print(f"wrote {len(rows)} publications to {OUT}")


if __name__ == "__main__":
    main()
